version: '3.1'
services:
  api_unsec:
    build: 
      context: app
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=api/app
  api_sec:
    build: 
      context: app_sec
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=api/app